Indexing and Slicing 2D Arrays in NumPy

In [1]:
import numpy as np
arr = np.arange(1, 26).reshape(5,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [2]:
print(arr[0,])

[1 2 3 4 5]


In [4]:
print(arr[-1])

[21 22 23 24 25]


In [5]:
print(arr[:,0])

[ 1  6 11 16 21]


In [6]:
print(arr[:,-1])

[ 5 10 15 20 25]


In [7]:
import numpy as np
arr = np.arange(1, 26).reshape(5,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [8]:
print([arr[1:3,1:3]])

[array([[ 7,  8],
       [12, 13]])]


In [10]:
print(arr[2:,2:])

[[13 14 15]
 [18 19 20]
 [23 24 25]]


In [11]:
print(arr[0::2])

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]


In [12]:
print(arr[:,0::2])

[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]]


In [13]:
print(arr[::-1])

[[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


In [14]:
print(arr[:,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]
 [20 19 18 17 16]
 [25 24 23 22 21]]


Indexing and Slicing 3D Arrays in NumPy

In [15]:
arr3 = np.arange(1,25).reshape(2,3,4)
print(arr3)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [17]:
print(arr3[0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
print(arr3[0,1])

[5 6 7 8]


In [19]:
print(arr3[1,1])

[17 18 19 20]


In [20]:
print(arr3[1,0,2])

15


In [21]:
print(arr3[0,1::,1:-1])

[[ 6  7]
 [10 11]]


In [22]:
arr3 = np.arange(1,25).reshape(2,3,4)
print(arr3)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [24]:
print(arr3[1,:,1:-1])

[[14 15]
 [18 19]
 [22 23]]


In [25]:
print(arr3[0:,:,-1])

[[ 4  8 12]
 [16 20 24]]


In [27]:
print(arr3[0:,0,])

[[ 1  2  3  4]
 [13 14 15 16]]


In [28]:
print(arr3[0:,1,1:3])

[[ 6  7]
 [18 19]]
